services:
  web:
    build: .
    image: fitness_studio:latest
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/fitness_studio
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
